config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users

  root to: 'homes#top'
  get 'users' => 'users#index'
  get 'home/about' => 'homes#about'

  resources :books do

   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'followings/:id' => 'users#followings', as: 'followings' #フォローしているユーザ一覧
  get 'follows/:id' => 'users#follows', as: 'follows' #フォローされているユーザ一覧

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_back(fallback_location: root_path) #非同期通信の為、一旦
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_back(fallback_location: root_path) #非同期通信の為、一旦消す
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
     <p>
      <%= link_to book_favorites_path(book.id), method: :delete, remote:true do %>
        ♥<%= book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post, remote:true do %>
        ♡<%= book.favorites.count %>
    </p>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorite_button<%=@book.id%>').html("<%= j(render partial: 'favorite', locals: { book: @book}) %>");

app/views/favorites/destroy.js.erb
$('.favorite_button<%=@book.id%>').html("<%= j(render partial: 'favorite', locals: { book: @book}) %>");