config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users

  root to: 'homes#top'
  get 'users' => 'users#index'
  get 'home/about' => 'homes#about'

  resources :books do

   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'followings/:id' => 'users#followings', as: 'followings' #フォローしているユーザ一覧
  get 'follows/:id' => 'users#follows', as: 'follows' #フォローされているユーザ一覧

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  validates :name, length: { in: 2..20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, { only: [:edit, :update, :destroy] }

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "successfully update"
    else
      render "edit"
    end
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def followings
  @user = User.find(params[:id])
  end

  def follows
  @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body,)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <p>error!!</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<h2>Editing Info</h2>
<%= form_with model:@user, local:true do |f| %>

  <h4>Name</h4>
    <%= f.text_field :name %>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
     <h4>Image</h4>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <h4>introduction</h4>
    <%= f.text_area :introduction %>

    <%= f.submit 'Update User' %>

<% end %>

app/views/users/followings.html.erb
<h3>Follow Users</h3>
<table class="table">
  <% @user.following_user.each do |user| %>
  <tr>
    <th><%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg" %></th>
    <th><%= user.name %></th>
    <th><%= "フォロー数: #{user.follower.count}" %></th>
    <th><%= "フォロワー数: #{user.followed.count}" %></th>
    <th>
      <% unless user == current_user %>
      <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
      <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <% end %>
    </th>
    <th><%= link_to "Show", user_path(user.id) %></th>
  </tr>
  <% end %>
</table>

app/views/users/follows.html.erb
<h3>Follower Users</h3>
<table class="table">
  <% @user.follower_user.each do |user| %>
  <tr>
    <th><%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg" %></th>
    <th><%= user.name %></th>
    <th><%= "フォロー数: #{user.follower.count}" %></th>
    <th><%= "フォロワー数: #{user.followed.count}" %></th>
    <th>
      <% unless user == current_user %>
      <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
      <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <% end %>
    </th>
    <th><%= link_to "Show", user_path(user.id) %></th>
  </tr>
  <% end %>
</table>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
 <div class="col-md-3">

<p id="notice">
  <%= notice %>
</p>

<% if @book.errors.any? %>
    <p>error!!</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>


 <h2>User info</h2>
   <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>
   <i class="fas fa-user-cog"></i>
   <%= link_to "editing info",edit_user_path(@user.id) %>




   <h2>New book</h2>
   <%= form_with model:@book, local:true do |f| %>
   <h3>Title</h3>
   <%= f.text_field :title %>
   <h3>Body</h3>
   <%= f.text_area :body %>
   <%= f.submit "Create Book" %>
   <% end %>
  </div>



<div class="col-md-8 offset-md-1">
<h2>Users</h2>

<table class="table">
  <% @users.each do |user| %>
  <tr>
    <th><%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg" %></th>
    <th><%= user.name %></th>
    <th><%= "フォロー数: #{user.follower.count}" %></th>
    <th><%= "フォロワー数: #{user.followed.count}" %></th>
    <th>
      <% unless user == current_user %>
      <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
      <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
      <% end %>
    </th>
    <th><%= link_to "Show", user_path(user.id) %></th>
  </tr>
  <% end %>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
<div class= "col-md-3">

<p id="notice">
  <%= notice %>
</p>

<% if @book.errors.any? %>
    <p>error!!</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %>
<h4>name</h4>
<%= @user.name %>
<h4>introduction</h4>
<%= @user.introduction %>
<p><i class="fas fa-user-cog"></i><%= link_to "editing info", edit_user_path(@user) %></p>

<p><%=link_to "フォロー数: #{@user.follower.count}", followings_path(@user) %></p>
<p><%=link_to "フォロワー数: #{@user.followed.count}", follows_path(@user) %></p>
<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
  <% else %>
    <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
  <% end %>
<% end %>


 <h2>New book</h2>
   <%= form_with model:@book, local:true do |f| %>
   <h3>Title</h3>
   <%= f.text_field :title %>
   <h3>Body</h3>
   <%= f.text_area :body %>
   <%= f.submit "Create Book" %>
   <% end %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">
  <tr>
    <th></th>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @books.each do |book| %>
   <tr>
     <td>
         <%= link_to user_path(@user.id) do %>
         <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %>
         <% end %>
     </td>
     <td><%=link_to book.title, book_path(book.id)%></td>
     <td><%=link_to book.body %></td>
     <td>
       <p>コメント件数：<%= book.book_comments.count %></p>
     </td>
   </tr>
  <% end %>
</table>
</div>
</div>
</div>