config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users

  root to: 'homes#top'
  get 'users' => 'users#index'
  get 'home/about' => 'homes#about'

  resources :books do

   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'followings/:id' => 'users#followings', as: 'followings' #フォローしているユーザ一覧
  get 'follows/:id' => 'users#follows', as: 'follows' #フォローされているユーザ一覧

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :destroy, :update]

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "successfully created"
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update book_params
      redirect_to book_path(@book), notice: "successfully edited"
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books", notice: "successfully deleted"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def baria_user
    unless Book.find(params[:id]).user.id.to_i == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<p id="notice">
  <%= notice %>
</p>

<% if @book.errors.any? %>
    <p>error</p>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

 <%= form_with model:@book, local:true do |f| %>
  <h2>Title</h2>
  <%= f.text_field :title %>
  <h2>Body</h2>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
 <% end %>

 <%= link_to "Show",book_path(@book.id)%>
 <%= link_to "Back",books_path %>

app/views/books/index.html.erb
<div class="container">
<div class="row">
<div class= "col-md-3">

<p id="notice">
  <%= notice %>
</p>

<% if @book.errors.any? %>
    <p>error!!</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>


 <h2>User info</h2>
   <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %>
   <i class="fas fa-user-cog"></i>
   <%= link_to "editing info",edit_user_path(@user.id) %>




   <h2>New book</h2>
   <%= form_with model:@book, local:true do |f| %>
   <h3>Title</h3>
   <%= f.text_field :title %>
   <h3>Body</h3>
   <%= f.text_area :body %>
   <%= f.submit "Create Book" %>
   <% end %>
  </div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">
  <tr>
    <th></th>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @books.each do |book| %>
   <tr>
     <td>
         <%= link_to user_path(book.user_id) do %>
         <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %>
         <% end %>
     </td>
     <td><%=link_to book.title, book_path(book.id)%></td>
     <td><%=link_to book.body %></td>
     <td>
     <div class="favorite_button<%=book.id%>">
       <%= render partial: 'favorites/favorite', locals: { book: book}%>
     </div>
     </td>
     <td>
      <p>コメント件数：<%= book.book_comments.count %></p>
     </td>
   </tr>
  <% end %>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<div class= "col-md-3">
<p id="notice">
  <%= notice %>
</p>

<% if @book.errors.any? %>
    <p>error!!</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>


<h2>User info</h2>

   <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   <h5>name</h5>
   <%= @book.user.name %>
   <h5>introduction</h5>
   <%= @book.user.introduction %>

   <i class="fas fa-user-cog"></i>
   <%= link_to"editing info",edit_user_path(@book.user.id) %>


   <h2>New book</h2>
   <%= form_with model:@book_new, local:true do |f| %>
   <h3>Title</h3>
   <%= f.text_field :title %>
   <h3>Body</h3>
   <%= f.text_area :body %>
   <%= f.submit "Create Book" %>
   <% end %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
  <table class='table'>
    <tr>
      <td>
      <%= link_to user_path(@book.user.id) do %>
      <%= attachment_image_tag @book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %>
      <nav><%= @book.user.name %></nav>
      <% end %>
      </td>
      <td><%= link_to @book.title %></td>
      <td><%= @book.body %></td>
      <td>
      <div class="favorite_button<%=@book.id%>">
       <%= render partial: 'favorites/favorite', locals: { book: @book}%>
      </div>
      </td>
      <td>
        コメント数：<span id="comments_count"><%= @book.book_comments.count %></span>
      </td>
      <% if @book.user.id == current_user.id %>
      <td><%=link_to"Edit", edit_book_path(@book.id) %></td>
      <td><%=link_to"Destroy", book_path(@book.id),method: :delete %> </td>
      <% end %>
    </tr>
  </table>


  <div id="comment">
    <%= render partial:'book_comments/comments', locals: {book_comments: @book_comment} %>
  </div>

  <div class="new-comment">
  <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
  <%= f.text_area :comment, rows:'5', id:"comment_content" %>
  <%= f.submit "送信する" %>
  <% end %>
  </div>
</div>
</div>
</div>